apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blueprint
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # important when applying CRs without their CRDs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: registry.cloudogu.com/k8s
      chart: k8s-blueprint
      targetRevision: "1.2.1"
      path: "."  # required for Helm OCI sources
  destination:
    server: https://kubernetes.default.svc
    namespace: ecosystem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true          # safer deletion